<?php
/**
 * @category     Inchoo
 * @package     Inchoo Featured Products
 * @author        Domagoj Potkoc, Inchoo Team <web@inchoo.net>
 * @modified    Mladen Lotar <mladen.lotar@surgeworks.com>, Vedran Subotic <vedran.subotic@surgeworks.com>
 */
?>

<?php $_columnCount = 3; ?>

<?php $image_size = (int) Mage::getStoreConfig("featuredproducts/cmspage/max_image_dimension") ?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class="featured category-products">

    <h3><?php echo $this->__($this->getBlockLabel()) ?></h3>

    <?php $i=3; if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
    <?php endif ?>
    
            <?php foreach ($_products->getItems() as $_product): ?>
            
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                    <img class="product-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image') ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                </a>
                <div class="product-description">
                    <p>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>)">
                            <?php echo $this->htmlEscape($_product->getName()) ?>
                        </a>
                    </p>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>

                    <?php if (Mage::getStoreConfig('featuredproducts/general/price_visible')): ?>

                        <?php echo $this->getPriceHtml($_product, true, '-new') ?>

                        <?php if ($_product->isSaleable()): ?>
                            <button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php else: ?>
                            <div class="out-of-stock"><?php echo $this->__('Out of stock') ?></div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
              
            </li>
           
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
